### ISSUE TITLE
What can I do when ws.html:142 queue.length > 100

### ISSUE THREAD

**Issue by waiter89** [david7482/fMP4-lib#6]
What can I do when ws.html:142    queue.length > 100  ?

and another question 
 (buffered_time > 1.5) {
                    //console.log("Too much buffered time which cause latency. Speed up the playback rate");
                    video.playbackRate = 1.2
 }
here playbackRate=1.2 has no effect in chrome

Thanks!

**Comment by david7482** [comment]
@waiter89 
It might mean your browser is not fast enough to consume your incoming data.
You might need to change to a smaller video size.

For the fast forward, I would suggest just jump to current playtime to catch up the delay.
